---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_name }}
  namespace: {{ cookiecutter.kubernetes_namespace }}
  annotations:
    manifest_path: "kubernetes/{{ cookiecutter.kubernetes_namespace }}/{{ cookiecutter.project_name }}/1_deployment.yml"
  labels:
    app: {{ cookiecutter.project_name }}
spec:
  replicas: {{ cookiecutter.kubernetes_replicas }}
  selector:
    matchLabels:
      app: {{ cookiecutter.project_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_name }}
    spec:
      containers:
        - name: {{ cookiecutter.project_name }}
          image: {{ cookiecutter.org_name }}/{{ cookiecutter.project_name }}:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ cookiecutter.project_name }}-secret
          ports:
            - name: http
              containerPort: {{ cookiecutter.kubernetes_port }}
              protocol: {{ cookiecutter.kubernetes_protocol }}
          livenessProbe:
            httpGet:
              path: {{ cookiecutter.kubernetes_endpoint_path_healthcheck }}
              port: {{ cookiecutter.kubernetes_port }}
          readinessProbe:
            httpGet:
              path: {{ cookiecutter.kubernetes_endpoint_path_healthcheck }}
              port: {{ cookiecutter.kubernetes_port }}
          resources:
            limits:
              cpu: {{ cookiecutter.max_cpu }}
              memory: {{ cookiecutter.max_mem }}
            requests:
              cpu: {{ cookiecutter.min_cpu }}
              memory: {{ cookiecutter.min_mem }}
      imagePullSecrets:
        - name: docker-secrets
      nodeSelector:
        cloud.google.com/gke-nodepool: "{{ cookiecutter.kubernetes_nodepool }}"
