---
apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_name }}
  namespace: {{ cookiecutter.kubernetes_namespace }}
spec:
  selector:
    app: {{ cookiecutter.project_name }}
  ports:
    - name: {{ cookiecutter.project_name }}
      protocol: {{ cookiecutter.kubernetes_protocol }}
      port: {{ cookiecutter.kubernetes_port }}
      targetPort: {{ cookiecutter.kubernetes_port }}
