---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ cookiecutter.project_name }}-{{ cookiecutter.project_env }}
  namespace: {{ cookiecutter.k8s_namespace }}
  labels:
    project: {{ cookiecutter.project_name }}
    environment: {{ cookiecutter.project_env }}
    team: {{ cookiecutter.project_team }}
    product-owner: {{ cookiecutter.project_owner }}
spec:
  destination:
    namespace: {{ cookiecutter.k8s_namespace }}
    server: https://kubernetes.default.svc
  project: {{ cookiecutter.project_team }}-project
  source:
    path: {{ cookiecutter.project_env }}/{{ cookiecutter.project_name }}
    repoURL: {{ cookiecutter.git_configs_repo }}
    targetRevision: HEAD
